unstoppabledomains/resolution-browser-extension

.gitignore, src/scripts/background.ts, static/manifest.json
1. Added support for bing and duckduckgo
2. Removed key in manifest that caused an error on extension load
3. Simplified adding more domains/search engines in the future
=> Search engines

src/internalPages/WebsitesList/Record.tsx, src/internalPages/WebsitesList/WeblistHeader.tsx, src/scripts/background.ts, src/util/helpers.ts
make sure we change the designated tab instead of the current window
=> Designated tab

CHANGELOG.md, src/internalPages/ExtensionMain/MainScreen.tsx, src/types.ts
According to https://ipfs.github.io/public-gateway-checker/ I added 4 more options for safe origin ipfs to choose from.
=> More gateway options

CHANGELOG.md, manifest-template.json, package.json, src/internalPages/WebsitesList/WeblistHeader.tsx, src/util/helpers.ts, yarn.lock
* Removed .eth from permission list (this will stop extension attempts to resolve the ens domains)
* Upgraded resolution library to 7.0.0
=> remove ens support

src/util/helpers.ts
- add .kresus to supported domains
=> feat: add .kresus to supported domains

manifest-template.json, package.json, src/util/helpers.ts, yarn.lock
fix .kresus resolution permission and added .klever support
=> fix: .kresus resolution permission and added .klever support

CHANGELOG.md, manifest-template.json
=> chore: update version and changelog

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
- add .binanceus to supported domains
=> feat: add .binanceus to supported domains

src/internalPages/ExtensionMain/MainScreen.tsx
The OAURL class is not imported, so it throws errors when it's trying to save the URL. It causes the bug that custom IPFS url is not saved.
- Import the OAURL class properly
=> fix: OAURL class import

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
- add .altimist to supported domains
=> feat: add .altimist to supported domains

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
- add .pudgy to supported tlds
=> feat: add .pudgy to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
When users enter a domain like abc.x in the browser, it leads to an URL like https://somehash.ipfs.somegateway.com// with the extra `/`. For Gateway provider like Infura, it will resolve to a wrong URL. This PR is to trim the extra `/`.
- Trim the extra / for redirect IPFS URL
=> fix: trim the extra / for redirect IPFS URL

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add support for .austin

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add support for .bitget

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add support for .pog

CHANGELOG.md, manifest-template.json, src/manifest.json, src/util/helpers.ts
=> feat: add support for .clay

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> [APIS-1722] metropolis tld

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add support for .secret

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add support for .raiin

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .stepn to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .kryptic to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .ubu to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .tball to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .dfz to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .smobler to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .lfg to supported tlds

CHANGELOG.md, manifest-template.json, src/util/helpers.ts
=> feat: add .dream to supported tlds

CHANGELOG.md, package.json, src/components/Root.tsx, src/lib/resolver/resolver.ts, src/lib/wallet/preferences.ts, src/pages/Legacy/Extension.tsx, src/pages/OnUpdated/index.tsx, src/pages/Wallet/Preferences.tsx, src/types/wallet/preferences.ts
- Improve Sherlock performance with wallet field flags
- Add configuration capability in non-wallet mode
=> Optimize Sherlock UX for non-wallet configuration

CHANGELOG.md, package.json, yarn.lock
Allow user to buy / sell crypto directly within the wallet user experience.
https://github.com/user-attachments/assets/6b38ebce-a5b9-4c05-bac0-fdc87a15ebe4
=> Bump @unstoppabledomains/ui-components for better onramp / offramp UX

CHANGELOG.md, package.json, src/lib/wallet/2fa.ts, src/lib/wallet/preferences.ts, src/pages/Wallet/Preferences.tsx, src/pages/Wallet/TwoFactorModal.tsx, src/types/wallet/preferences.ts
From the settings panel, allow the user to enable / disable the 2FA feature. Currently gated by a feature flag, until we are ready to roll this out as part of the sign-in experience.
https://github.com/user-attachments/assets/8b56d51d-e5fc-4b9f-8018-310c191972e4
=> Enroll 2FA from settings panel

package.json, yarn.lock
=> Integrated swap UX using Swing.xyz

.env.production, CHANGELOG.md, package.json, src/pages/Wallet/Connect.tsx, yarn.lock
Resolves a corner case when connecting to dapps, where the confirmation text was not properly displayed in the popup.
=> Fix app connection bug

.github/workflows/pr.yml
Email from Github Dec 10th, 2024:
Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact. After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.
=> [SRE-1497] update github workflows  to upload-artifact@v4

CHANGELOG.md, package.json, yarn.lock
* Automatically refresh tokens if extension is idle for long periods of time
* Fix bug when selecting certain tokens to send from the home screen
* Fix bug related to selecting swap tokens identified by contract address
=> Update packages with bug fixes

CHANGELOG.md, package.json, yarn.lock
When clicking a token, display a token detail page with options to receive, send, swap and buy.
=> Token detail page

CHANGELOG.md, package.json, scripts/create_manifest.js, yarn.lock
Title:
> UP.io - watch your crypto grow up
Description:
> Manage your digital assets with confidence while enjoying a user-friendly experience. Supports Bitcoin, Solana, Ethereum, Base and Polygon.
=> [UDM-269] Update copy for UP.io manifest

package.json, src/lib/wallet/message.ts, src/scripts/liteWalletProvider/background.ts, src/scripts/liteWalletProvider/main.ts, src/types/wallet/provider.ts, yarn.lock
Internal changes to event management to ensure concurrent versions of the extension can exist within the same browser runtime.
=> Additional namespace checking for concurrent extension runtime

CHANGELOG.md, package.json, yarn.lock
Ensure the "support" button takes users to the new UP.io documentation landing page.
=> update support page link

CHANGELOG.md, package.json, yarn.lock
brings XMTP to the latest level to resolve some protocol bugs.
=> bump XMTP version

client.jest.config.ts, package.json, yarn.lock
Update package versions to remove Bugsnag library usage.
=> Update packages to reemove bugsnag usage
